name: Blob storage website CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:            
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1.2.0
      with:
        node-version: '12.x'

    - name: Install dependencies
      run: npm install --production

    - name: Compile build
      run: npm run build

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
            az storage blob upload-batch --account-name cirtausawebcontent --account-key ${{ secrets.AZURE_CREDENTIALS }} -d '$web' -s output

  # Azure logout 
    - name: logout
      run: |
            az logout